[package]
name = "analysis"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
publish = false

[lib]
test = false
doctest = false

[dependencies]
config = { path = "../config" }
diagnostic-util = { git = "https://github.com/azdavis/language-util.git" }
elapsed = { git = "https://github.com/azdavis/language-util.git" }
fmt-util = { git = "https://github.com/azdavis/language-util.git" }
input = { path = "../input" }
mlb-statics = { path = "../mlb-statics" }
paths = { git = "https://github.com/azdavis/language-util.git" }
sml-file-syntax = { path = "../sml-file-syntax" }
sml-fixity = { path = "../sml-fixity" }
sml-fmt = { path = "../sml-fmt" }
sml-hir = { path = "../sml-hir" }
sml-namespace = { path = "../sml-namespace" }
sml-statics = { path = "../sml-statics" }
sml-syntax = { path = "../sml-syntax" }
str-util = { git = "https://github.com/azdavis/language-util.git" }
text-pos = { git = "https://github.com/azdavis/language-util.git" }
text-size-util = { git = "https://github.com/azdavis/language-util.git" }
