[package]
name = "analysis"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
publish = false

[lib]
test = false
doctest = false

[dependencies]
cm-syntax = { path = "../cm-syntax" }
config = { path = "../config" }
diagnostic-util = { path = "../diagnostic-util" }
elapsed = { path = "../elapsed" }
fast-hash = { path = "../fast-hash" }
fmt-util = { path = "../fmt-util" }
log = "0.4"
mlb-statics = { path = "../mlb-statics" }
mlb-syntax = { path = "../mlb-syntax" }
paths = { path = "../paths" }
sml-fmt = { path = "../sml-fmt" }
sml-hir = { path = "../sml-hir" }
sml-parse = { path = "../sml-parse" }
sml-statics = { path = "../sml-statics" }
sml-syntax = { path = "../sml-syntax" }
str-util = { path = "../str-util" }
text-pos = { git = "https://github.com/azdavis/language-util.git" }
text-size-util = { path = "../text-size-util" }
toml = "0.5"
topo-sort = { git = "https://github.com/azdavis/language-util.git" }
