[package]
name = "mlb-hir"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true

[lib]
test = false
doctest = false

[dependencies]
fast-hash = { git = "https://github.com/azdavis/language-util.git" }
paths = { git = "https://github.com/azdavis/language-util.git" }
sml-namespace = { path = "../sml-namespace" }
str-util = { git = "https://github.com/azdavis/language-util.git" }
text-size-util = { git = "https://github.com/azdavis/language-util.git" }
