[package]
name = "mlb-hir"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
publish = false

[lib]
test = false
doctest = false

[dependencies]
fast-hash = { path = "../fast-hash" }
paths = { path = "../paths" }
sml-namespace = { path = "../sml-namespace" }
str-util = { path = "../str-util" }
text-size-util = { path = "../text-size-util" }
