[package]
name = "cov-mark"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true

[lib]
test = false
doctest = false

[dependencies]
once_cell = "1"
fast-hash = { git = "https://github.com/azdavis/language-util.git" }
