(*!
The structure Posix.Error provides symbolic names for errors that may be generated by the POSIX
library, and various related functions.
!*)
signature POSIX_ERROR = sig
  (*!
  POSIX error type. This is identical to the type OS.syserror.
  !*)
  eqtype syserror = OS.syserror
  (*!
  These functions convert between syserror values and non-zero word representations. Note that there
  is no validation that a syserror value generated using fromWord corresponds to an error value
  supported by the underlying system.
  !*)
  val toWord : syserror -> SysWord.word
  val fromWord : SysWord.word -> syserror
  (*!
  errorMsg sy returns a string that describes the system error sy.
  !*)
  val errorMsg : syserror -> string
  (*!
  errorName err returns a unique name used for the syserror value.
  !*)
  val errorName : syserror -> string
  (*!
  syserror s returns the syserror whose name is s if it exists. If e is a syserror, we have SOME(e)
  = syserror(errorName e).
  !*)
  val syserror : string -> syserror option
  val acces : syserror
  val again : syserror
  val badf : syserror
  val badmsg : syserror
  val busy : syserror
  val canceled : syserror
  val child : syserror
  val deadlk : syserror
  val dom : syserror
  val exist : syserror
  val fault : syserror
  val fbig : syserror
  val inprogress : syserror
  val intr : syserror
  val inval : syserror
  val io : syserror
  val isdir : syserror
  val loop : syserror
  val mfile : syserror
  val mlink : syserror
  val msgsize : syserror
  val nametoolong : syserror
  val nfile : syserror
  val nodev : syserror
  val noent : syserror
  val noexec : syserror
  val nolck : syserror
  val nomem : syserror
  val nospc : syserror
  val nosys : syserror
  val notdir : syserror
  val notempty : syserror
  val notsup : syserror
  val notty : syserror
  val nxio : syserror
  val perm : syserror
  val pipe : syserror
  val range : syserror
  val rofs : syserror
  val spipe : syserror
  val srch : syserror
  val toobig : syserror
  val xdev : syserror
end

structure Error : POSIX_ERROR = struct end
