[package]
name = "sml-syntax"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true

[lib]
test = false
doctest = false

[dependencies]
rowan.workspace = true
token.workspace = true

[build-dependencies]
char-name.workspace = true
code-h2-md-map.workspace = true
fast-hash.workspace = true
identifier-case.workspace = true
syntax-gen.workspace = true
