[package]
name = "sml-syntax"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
publish = false

[lib]
test = false
doctest = false

[dependencies]
rowan = { git = "https://github.com/azdavis/rowan.git" }
token = { git = "https://github.com/azdavis/language-util.git" }

[build-dependencies]
char-name = { git = "https://github.com/azdavis/language-util.git" }
fast-hash = { git = "https://github.com/azdavis/language-util.git" }
code-h2-md-map = { git = "https://github.com/azdavis/language-util.git" }
identifier-case = { git = "https://github.com/azdavis/language-util.git" }
syntax-gen = { git = "https://github.com/azdavis/language-util.git" }
