[package]
name = "sml-hir"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
publish = false

[lib]
doctest = false
test = false

[dependencies]
la-arena = "0.3"
num-bigint = "0.4"
str-util = { git = "https://github.com/azdavis/language-util.git" }
