[package]
name = "sml-hir-shared"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true

[lib]
doctest = false
test = false

[dependencies]
num-bigint = "0.4"
num-traits = "0.2"
str-util = { git = "https://github.com/azdavis/language-util.git" }
