[package]
name = "chain-map"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true

[lib]
test = false
doctest = false

[dependencies]
fast-hash.workspace = true
str-util.workspace = true

[features]
sync = []
