[package]
name = "sml-fixity"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true

[lib]
doctest = false
test = false

[dependencies]
fast-hash.workspace = true
once_cell = "1"
str-util.workspace = true
